# Setup
title:               DataManiac
tagline:             'A dump/blog for my thoughts on anything data'
description:         'Special credits for this Lanyon design goes to <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 "https://chuazy94.github.io"
baseurl:             "zy_blog_2"
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Zhi Yuan Chua
  url:               https://twitter.com/chuazyyy
  email:             zhiyuanchua2806@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
