source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-paginate"
gem "jekyll-seo-tag"
gem "jekyll-gist"
gem "jekyll-remote-theme"
gem "jekyll-include-cache"
gem "minimal-mistakes-jekyll"
gem "webrick"
